import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gray-100">
          <header className="bg-white shadow-sm p-4">
            <div className="max-w-7xl mx-auto">
              <h1 className="text-3xl font-bold text-center">SynCanvas</h1>
              <p className="text-center text-gray-600">
                Discover the perfect musical companion for classic artworks
              </p>
            </div>
          </header>
          <main className="max-w-7xl mx-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
